### ISSUE TITLE
Video Pins Problem... Unable to post video pins

### ISSUE THREAD

**Issue by ibikhan1234** [bstoilov/py3-pinterest#167] opened 2022-01-18 12:40 UTC
The code is working fine for image pins, but when it comes to Video pins, there is no function that is specific for uploading video pins.

**Comment by bstoilov** [comment] 2022-05-03 16:41
Duplicate of this one
https://github.com/bstoilov/py3-pinterest/issues/147

**Closed by bstoilov** 2022-05-03 16:41 UTC
Labels: feature request

**Comment by ibikhan1234** [comment] 2022-05-04 00:49
But you did not provide the solution. I thin, it can be done by changing the headers to multipart for video files and those headers can be found in inspect mode in chrome when uploading video pins, but i am unable to do it. can you please resolve this issue of uploading video pins?

**Comment by bstoilov** [comment] 2022-05-04 13:08
I just noticed that uploading video pins is feature of business accounts, this script still doen't support them
