### ISSUE TITLE
unable to start the bot

### ISSUE THREAD

**Issue by khansaad1275** [bstoilov/py3-pinterest#45] opened 2020-02-01 07:46 UTC
i am getting this error, can anyone please help me.
Traceback (most recent call last):
  File "F:\new\py3-pinterest-master\examples.py", line 10, in <module>
    pinterest.login()
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 118, in login
    return self.post(url=CREATE_USER_SESSION, data=data)
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 106, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 98, in request
    response.raise_for_status()
  File "C:\Users\12345\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/UserSessionResource/create/
>>> 
============== RESTART: F:\new\py3-pinterest-master\examples.py ==============
Traceback (most recent call last):
  File "F:\new\py3-pinterest-master\examples.py", line 10, in <module>
    pinterest.login()
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 118, in login
    return self.post(url=CREATE_USER_SESSION, data=data)
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 106, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "F:\new\py3-pinterest-master\py3pin\Pinterest.py", line 98, in request
    response.raise_for_status()
  File "C:\Users\12345\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.pinterest.com/resource/UserSessionResource/create/

**Comment by bstoilov** [comment] 2020-02-02 12:48
`429 Client Error: Too Many Requests for url`
you tried to login too many times and got temporary banned.

`login()` should be called only when the session expires, which is when you start receiving unauthorized responses from the rest of the endpoints

**Comment by bstoilov** [comment] 2020-03-09 09:07
Closing this, open new one if the issue is still there

**Closed by bstoilov** 2020-03-09 09:07 UTC
