### ISSUE TITLE
email error message

### ISSUE THREAD

**Issue by paullovachy** [bstoilov/py3-pinterest#30] opened 2019-12-12 18:41 UTC
Getting the following error when trying to create new instance by running the following:
pinterest = Pinterest(email='your email goes here', password='password goes here', username='look in pinterest url', cred_root='cred root dir')

error message: TypeError: __init__() got an unexpected keyword argument 'email'

Not sure what is going wrong here (of course I am replacing the value with my own email, password etc.)

**Comment by bstoilov** [comment] 2019-12-12 20:48
This is strange, can you make sure the version of py3-pinterest is the latest

**Comment by paullovachy** [comment] 2019-12-12 20:54
I think maybe something with another library - probably my issue - will confirm!

**Comment by bstoilov** [comment] 2020-06-20 10:35
Will close this since it seem the issue is resolved.

**Closed by bstoilov** 2020-06-20 10:35 UTC
Labels: bug

**Comment by sjaydeep** [comment] 2020-11-10 05:54
i faces same issue . yesterday it was working and today i got this error from the every methods.
TypeError: __new__() got an unexpected keyword argument 'email'
